<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ed-fi.org/5.2.0" xmlns:ann="http://ed-fi.org/annotation" targetNamespace="http://ed-fi.org/5.2.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:include schemaLocation="Ed-Fi-Core.xsd" />
  <xs:annotation>
    <xs:documentation>===== Ed-Fi 5.2.0 Extensions =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== Domain Entities =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-IDEAEvent">
    <xs:annotation>
      <xs:documentation>An IDEA related student event describing status, dates and narrative.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Domain Entity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IDEAEventID" type="EXTENSION-IDEAEventID">
            <xs:annotation>
              <xs:documentation>A unique identifier for the event record as assigned by the provider of IEP services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="EducationOrganizationReference" type="EducationOrganizationReferenceType">
            <xs:annotation>
              <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IDEA Services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IDEAEvent" type="EXTENSION-IDEAEventDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The IDEA event recorded for the student.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-IDEAEventDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="EventBeginDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The date when the IDEA related event started.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="EventEndDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The date when the IDEA event concluded.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="EventReason" type="EXTENSION-EventReasonDescriptorReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The reason why the IDEA event occured.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-EventReasonDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="EventCompliance" type="EXTENSION-EventComplianceDescriptorReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The type of compliance represented by this event.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-EventComplianceDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="EventNarrative" type="EXTENSION-EventNarrative" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Detailed and summary notes recorded during the event.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEP">
    <xs:annotation>
      <xs:documentation>This association describes summary IEP data for a student receiving special education services.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Domain Entity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="IEPServicingEducationOrganizationReference" type="EducationOrganizationReferenceType">
            <xs:annotation>
              <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IEP Services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentIEPAssociationID" type="EXTENSION-StudentIEPAssociationID">
            <xs:annotation>
              <xs:documentation>A unique identifier assigned by the provider or source system of IEP services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPFinalizedDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The date the most recent IEP was finalized.  Note: Date interpretation may vary. Ed-Fi recommends inclusive dates, but states may define dates as inclusive or exclusive. For calculations, align with local guidelines.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPBeginDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The effective start date of the most recent IEP.  Note: Date interpretation may vary. Ed-Fi recommends inclusive dates, but states may define dates as inclusive or exclusive. For calculations, align with local guidelines.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPEndDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The effective end date of the most recent IEP.  Note: Date interpretation may vary. Ed-Fi recommends inclusive dates, but states may define dates as inclusive or exclusive. For calculations, align with local guidelines.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPStatus" type="EXTENSION-IEPStatusDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The current status of the most recent IEP.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-IEPStatusDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPAmendedDate" type="xs:date" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The date when the most recent IEP was last amended, if any.  Note: Date interpretation may vary. Ed-Fi recommends inclusive dates, but states may define dates as inclusive or exclusive. For calculations, align with local guidelines.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="MedicallyFragile" type="xs:boolean" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Indicates whether the student receiving special education and related services is: 1) in the age range of birth to 22 years, and 2) has a serious, ongoing illness or a chronic condition that has lasted or is anticipated to last at least 12 or more months or has required at least one month of hospitalization, and that requires daily, ongoing medical treatments and monitoring by appropriately trained personnel which may include parents or other family members, and 3) requires the routine use of medical device or of assistive technology to compensate for the loss of usefulness of a body function needed to participate in activities of daily living, and 4) lives with ongoing threat to his or her continued well-being. Aligns with federal requirements.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="MultiplyDisabled" type="xs:boolean" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Indicates whether the student receiving special education and related services has been designated as multiply disabled by the admission, review, and dismissal committee as aligned with federal requirements.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="ReasonExited" type="ReasonExitedDescriptorReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The reason the student left and stop receiving special education services.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>ReasonExitedDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="SchoolHoursPerWeek" type="HoursPerWeek" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Indicates the total number of hours of instructional time per week for the school that the student attends.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="SpecialEducationSetting" type="SpecialEducationSettingDescriptorReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The major instructional setting (more than 50 percent of a student's special education program).</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>SpecialEducationSettingDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="SpecialEducationHoursPerWeek" type="HoursPerWeek" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Indicates the total number of hours of time per week specific to special education related services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IDEAEventReference" type="EXTENSION-IDEAEventReferenceType" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>A reference to one or more student IDEA events.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Descriptors =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-DurationPeriodDescriptor">
    <xs:annotation>
      <xs:documentation>The frequency period for the prescribed service duration. Examples include: Per Session, Per Week, Per Month.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-EventComplianceDescriptor">
    <xs:annotation>
      <xs:documentation>The policy or law for which an event is compliant.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-EventReasonDescriptor">
    <xs:annotation>
      <xs:documentation>Reason the event occured.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-FrequencyPeriodDescriptor">
    <xs:annotation>
      <xs:documentation>The frequency period for the prescribed service. Examples include: Session, Week, Month.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-IDEAEventDescriptor">
    <xs:annotation>
      <xs:documentation>IDEA event type. Examples: Referral for Evaluation, IEP Approved, Parental COnsent Given, Evaluation Complete.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-IEPGoalDescriptor">
    <xs:annotation>
      <xs:documentation>A focused goal for an IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-IEPStatusDescriptor">
    <xs:annotation>
      <xs:documentation>The current status of the student IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-ServiceComplianceDescriptor">
    <xs:annotation>
      <xs:documentation>The policy or law for which a prescribed service is compliant.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-ServiceDeliveryDescriptor">
    <xs:annotation>
      <xs:documentation>The type of service provided to a student.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-ServiceLocationTypeDescriptor">
    <xs:annotation>
      <xs:documentation>The location type where the prescribed service is to be provided. Examples include: Home, Hospital, School.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-ServicePrescriptionDescriptor">
    <xs:annotation>
      <xs:documentation>The type of service prescribed.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-ServiceProviderTypeDescriptor">
    <xs:annotation>
      <xs:documentation>Indicates service provider type, including specialist, internal staff, external staff, etc.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-ServiceReasonDescriptor">
    <xs:annotation>
      <xs:documentation>Reason the service was prescribed. Examples include: Counselor Assigned, IEP Team Determination.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Associations =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-IEPServicePrescription">
    <xs:annotation>
      <xs:documentation>The service prescribed to a student as part of their IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Association</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
            <xs:annotation>
              <xs:documentation>The student IEP for which the service is prescribed.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServicePrescription" type="EXTENSION-ServicePrescriptionDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The type of service prescribed. Examples include: Auditory Specialist, Vocational Therapy.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-ServicePrescriptionDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServicePrescriptionDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The date the service was prescribed.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="BeginDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The effective date when service is to begin.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="EndDate" type="xs:date" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The effective date when the prescribed service ended.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DurationMinutes" type="EXTENSION-DurationMinutes">
            <xs:annotation>
              <xs:documentation>The length of time for the prescribed service in minutes.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="DurationPeriod" type="EXTENSION-DurationPeriodDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The frequency period for the prescribed service duration. Examples include: Per Session, Per Week, Per Month.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-DurationPeriodDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="FrequencyValue" type="EXTENSION-FrequencyValue">
            <xs:annotation>
              <xs:documentation>The number of times the prescribed service is to be provided within the specified duration period.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="FrequencyPeriod" type="EXTENSION-FrequencyPeriodDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The frequency period for the prescribed service. Examples include: Session, Week, Month.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-FrequencyPeriodDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServiceLocationType" type="EXTENSION-ServiceLocationTypeDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The location type where the prescribed service is to be provided. Examples include: Home, Hospital, School.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-ServiceLocationTypeDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServiceProvidingEducationOrganizationReference" type="EducationOrganizationReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing prescribed services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StaffReference" type="StaffReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>A reference to the staff member providing the prescribed service.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IDEAEventReference" type="EXTENSION-IDEAEventReferenceType" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>A reference to one or more student IDEA events.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPAccommodation">
    <xs:annotation>
      <xs:documentation>The accommodations prescribed to a student as part of their IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Association</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
            <xs:annotation>
              <xs:documentation>The student IEP for which the accommodations are prescribed.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPServicingEducationOrganizationReference" type="EducationOrganizationReferenceType">
            <xs:annotation>
              <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IEP Services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Accommodation" type="AccommodationDescriptorReferenceType" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>The special variation(s) to be used in how various services (in general) are presented, how they are administered, or how the student is allowed to respond. This generally refers to changes that do not substantially alter the content that the service renders. The proper use of accommodations does not substantially change academic level or performance criteria.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>AccommodationDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPDisability">
    <xs:annotation>
      <xs:documentation>The disabilities prescribed to a student as part of their IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Association</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
            <xs:annotation>
              <xs:documentation>The student IEP for which the disability is prescribed.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPServicingEducationOrganizationReference" type="EducationOrganizationReferenceType">
            <xs:annotation>
              <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IEP Services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Disability" type="Disability" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>The disability condition(s) that best describes an individual's impairment, as related to special education services received.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPGoal">
    <xs:annotation>
      <xs:documentation>A goal prescribed to a student as part of their IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Association</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
            <xs:annotation>
              <xs:documentation>The student IEP for which the goal is prescribed.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPGoalID" type="EXTENSION-IEPGoalID">
            <xs:annotation>
              <xs:documentation>A unique identifier assigned by the provider of IEP services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPGoal" type="EXTENSION-IEPGoalDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>A focused goal prescribed as part of the IEP. Examples include Academic Goal, Behavioral Goal, Attendance Goal.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-IEPGoalDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPGoalDetails" type="EXTENSION-IEPGoalDetails">
            <xs:annotation>
              <xs:documentation>Instructions or other details specific to the student and/or provider for achieving the stated goal.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="GoalAchievementPeriodBeginDate" type="xs:date" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The first date of the period assigned for achieving the stated goal.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="GoalAchievementPeriodEndDate" type="xs:date" minOccurs="0">
            <xs:annotation>
              <xs:documentation>The last date of the period assigned for achieving the stated goal.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IDEAEventReference" type="EXTENSION-IDEAEventReferenceType" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>A reference to one or more student IDEA events.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPServiceDelivery">
    <xs:annotation>
      <xs:documentation>Services delivered to a student as prescribed by their IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Association</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ComplexObjectType">
        <xs:sequence>
          <xs:element name="StudentReference" type="StudentReferenceType">
            <xs:annotation>
              <xs:documentation>A reference to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
            <xs:annotation>
              <xs:documentation>The student and IEP associated with the delivery of prescribed services.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPServiceDeliveryID" type="EXTENSION-IEPServiceDeliveryID">
            <xs:annotation>
              <xs:documentation>A unique identifier assigned by the provider of IEP services for the delivery record.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServiceDelivery" type="EXTENSION-ServiceDeliveryDescriptorReferenceType">
            <xs:annotation>
              <xs:documentation>The type of services delivered to the student.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-ServiceDeliveryDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServiceDeliveryDate" type="xs:date">
            <xs:annotation>
              <xs:documentation>The date when prescribed services were delivered for a student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IEPServicePrescriptionReference" type="EXTENSION-IEPServicePrescriptionReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identifies the service prescribed for the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServiceProviderType" type="EXTENSION-ServiceProviderTypeDescriptorReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Indicates service provider type, including specialist, internal staff, external staff, etc.</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-ServiceProviderTypeDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
          <xs:element name="ServiceProvider" type="ServiceProvider" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>The internal service provider that delivered the prescribed service to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="ExternalServiceProvider" type="EXTENSION-ExternalServiceProvider" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>The external service provider that delivered the prescribed service to the student.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="IDEAEventReference" type="EXTENSION-IDEAEventReferenceType" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
              <xs:documentation>A reference to one or more student IDEA events.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Extended Reference Types =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-IDEAEventIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of an IDEAEvent.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IDEAEventID" type="EXTENSION-IDEAEventID">
        <xs:annotation>
          <xs:documentation>A unique identifier for the event record as assigned by the provider of IEP services.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="EducationOrganizationReference" type="EducationOrganizationReferenceType">
        <xs:annotation>
          <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IDEA Services.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IDEAEvent" type="EXTENSION-IDEAEventDescriptorReferenceType">
        <xs:annotation>
          <xs:documentation>The IDEA event recorded for the student.</xs:documentation>
          <xs:appinfo>
            <ann:Descriptor>EXTENSION-IDEAEventDescriptor</ann:Descriptor>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-IDEAEventReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for an IDEAEvent. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="IDEAEventIdentity" type="EXTENSION-IDEAEventIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of an IDEAEvent.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-IEPServicePrescriptionIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of an IEPServicePrescription.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
        <xs:annotation>
          <xs:documentation>The student IEP for which the service is prescribed.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ServicePrescription" type="EXTENSION-ServicePrescriptionDescriptorReferenceType">
        <xs:annotation>
          <xs:documentation>The type of service prescribed. Examples include: Auditory Specialist, Vocational Therapy.</xs:documentation>
          <xs:appinfo>
            <ann:Descriptor>EXTENSION-ServicePrescriptionDescriptor</ann:Descriptor>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ServicePrescriptionDate" type="xs:date">
        <xs:annotation>
          <xs:documentation>The date the service was prescribed.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-IEPServicePrescriptionReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for an IEPServicePrescription. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="IEPServicePrescriptionIdentity" type="EXTENSION-IEPServicePrescriptionIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of an IEPServicePrescription.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPAccommodationIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of a StudentIEPAccommodation.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
        <xs:annotation>
          <xs:documentation>The student IEP for which the accommodations are prescribed.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IEPServicingEducationOrganizationReference" type="EducationOrganizationReferenceType">
        <xs:annotation>
          <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IEP Services.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPAccommodationReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for a StudentIEPAccommodation. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="StudentIEPAccommodationIdentity" type="EXTENSION-StudentIEPAccommodationIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of a StudentIEPAccommodation.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPDisabilityIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of a StudentIEPDisability.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
        <xs:annotation>
          <xs:documentation>The student IEP for which the disability is prescribed.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IEPServicingEducationOrganizationReference" type="EducationOrganizationReferenceType">
        <xs:annotation>
          <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IEP Services.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPDisabilityReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for a StudentIEPDisability. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="StudentIEPDisabilityIdentity" type="EXTENSION-StudentIEPDisabilityIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of a StudentIEPDisability.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPGoalIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of a StudentIEPGoal.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
        <xs:annotation>
          <xs:documentation>The student IEP for which the goal is prescribed.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IEPGoalID" type="EXTENSION-IEPGoalID">
        <xs:annotation>
          <xs:documentation>A unique identifier assigned by the provider of IEP services.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPGoalReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for a StudentIEPGoal. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="StudentIEPGoalIdentity" type="EXTENSION-StudentIEPGoalIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of a StudentIEPGoal.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of a StudentIEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="IEPServicingEducationOrganizationReference" type="EducationOrganizationReferenceType">
        <xs:annotation>
          <xs:documentation>The identifier assigned to the education organization (usually District/LEA) providing IEP Services.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentIEPAssociationID" type="EXTENSION-StudentIEPAssociationID">
        <xs:annotation>
          <xs:documentation>A unique identifier assigned by the provider or source system of IEP services.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IEPFinalizedDate" type="xs:date">
        <xs:annotation>
          <xs:documentation>The date the most recent IEP was finalized.  Note: Date interpretation may vary. Ed-Fi recommends inclusive dates, but states may define dates as inclusive or exclusive. For calculations, align with local guidelines.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for a StudentIEP. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="StudentIEPIdentity" type="EXTENSION-StudentIEPIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of a StudentIEP.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPServiceDeliveryIdentityType">
    <xs:annotation>
      <xs:documentation>Identity of a StudentIEPServiceDelivery.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Identity</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="StudentReference" type="StudentReferenceType">
        <xs:annotation>
          <xs:documentation>A reference to the student.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="StudentIEPReference" type="EXTENSION-StudentIEPReferenceType">
        <xs:annotation>
          <xs:documentation>The student and IEP associated with the delivery of prescribed services.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="IEPServiceDeliveryID" type="EXTENSION-IEPServiceDeliveryID">
        <xs:annotation>
          <xs:documentation>A unique identifier assigned by the provider of IEP services for the delivery record.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ServiceDelivery" type="EXTENSION-ServiceDeliveryDescriptorReferenceType">
        <xs:annotation>
          <xs:documentation>The type of services delivered to the student.</xs:documentation>
          <xs:appinfo>
            <ann:Descriptor>EXTENSION-ServiceDeliveryDescriptor</ann:Descriptor>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ServiceDeliveryDate" type="xs:date">
        <xs:annotation>
          <xs:documentation>The date when prescribed services were delivered for a student.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EXTENSION-StudentIEPServiceDeliveryReferenceType">
    <xs:annotation>
      <xs:documentation>Provides alternative references for a StudentIEPServiceDelivery. Use XML IDREF to reference a record that is included in the interchange. Use the identity type to look up a record that was loaded previously.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="ReferenceType">
        <xs:sequence>
          <xs:element name="StudentIEPServiceDeliveryIdentity" type="EXTENSION-StudentIEPServiceDeliveryIdentityType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Identity of a StudentIEPServiceDelivery.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Extended Descriptor Reference Types =====</xs:documentation>
  </xs:annotation>
  <xs:simpleType name="EXTENSION-DurationPeriodDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The frequency period for the prescribed service duration. Examples include: Per Session, Per Week, Per Month.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-EventComplianceDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The policy or law for which an event is compliant.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-EventReasonDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>Reason the event occured.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-FrequencyPeriodDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The frequency period for the prescribed service. Examples include: Session, Week, Month.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IDEAEventDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>IDEA event type. Examples: Referral for Evaluation, IEP Approved, Parental COnsent Given, Evaluation Complete.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IEPGoalDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>A focused goal for an IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IEPStatusDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The current status of the student IEP.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ServiceComplianceDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The policy or law for which a prescribed service is compliant.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ServiceDeliveryDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The type of service provided to a student.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ServiceLocationTypeDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The location type where the prescribed service is to be provided. Examples include: Home, Hospital, School.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ServicePrescriptionDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>The type of service prescribed.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ServiceProviderTypeDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>Indicates service provider type, including specialist, internal staff, external staff, etc.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ServiceReasonDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>Reason the service was prescribed. Examples include: Counselor Assigned, IEP Team Determination.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:annotation>
    <xs:documentation>===== Common Types =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-ExternalServiceProvider">
    <xs:annotation>
      <xs:documentation>A service provider that is external to the education organization and is not present in the Staffs resource.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Common</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ProviderCode" type="EXTENSION-ProviderCode">
        <xs:annotation>
          <xs:documentation>A code assigned to the external service provider.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProviderFirstName" type="EXTENSION-ProviderFirstName">
        <xs:annotation>
          <xs:documentation>The first name of the external service provider.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProviderLastSurname" type="EXTENSION-ProviderLastSurname">
        <xs:annotation>
          <xs:documentation>The last name of the external service provider.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ProviderMiddleName" type="EXTENSION-ProviderMiddleName" minOccurs="0">
        <xs:annotation>
          <xs:documentation>The middle name of the external service provider.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="PrimaryProvider" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Primary External Service Provider.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Enumerations and Enumerated Collections =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== String Simple Types =====</xs:documentation>
  </xs:annotation>
  <xs:simpleType name="EXTENSION-EventNarrative">
    <xs:annotation>
      <xs:documentation>Detailed and summary notes recorded during the event.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="2048" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IDEAEventID">
    <xs:annotation>
      <xs:documentation>A unique identifier for the event record as assigned by the provider of IEP services.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IEPGoalDetails">
    <xs:annotation>
      <xs:documentation>Instructions or other details specific to the student and/or provider for achieving the stated goal.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="2048" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IEPGoalID">
    <xs:annotation>
      <xs:documentation>A unique identifier assigned by the provider of IEP services.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="256" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-IEPServiceDeliveryID">
    <xs:annotation>
      <xs:documentation>A unique identifier assigned by the provider of IEP services for the delivery record.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ProviderCode">
    <xs:annotation>
      <xs:documentation>A code assigned to the external service provider.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ProviderFirstName">
    <xs:annotation>
      <xs:documentation>The first name of the external service provider.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ProviderLastSurname">
    <xs:annotation>
      <xs:documentation>The last name of the external service provider.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-ProviderMiddleName">
    <xs:annotation>
      <xs:documentation>The middle name of the external service provider.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-StudentIEPAssociationID">
    <xs:annotation>
      <xs:documentation>A unique identifier assigned by the provider or source system of IEP services.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:maxLength value="1024" />
    </xs:restriction>
  </xs:simpleType>
  <xs:annotation>
    <xs:documentation>===== Numeric Simple Types =====</xs:documentation>
  </xs:annotation>
  <xs:simpleType name="EXTENSION-DurationMinutes">
    <xs:annotation>
      <xs:documentation>The length of time for the prescribed service in minutes.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="5" />
      <xs:fractionDigits value="2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EXTENSION-FrequencyValue">
    <xs:annotation>
      <xs:documentation>The number of times the prescribed service is to be provided within the specified duration period.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Simple</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="5" />
      <xs:fractionDigits value="2" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
