CREATE UNIQUE INDEX IF NOT EXISTS UX_a16a88_Id ON sedm.IDEAEvent(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_3d4921_Id ON sedm.IEPServicePrescription(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_d153ae_Id ON sedm.StudentIEP(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_9be3b5_Id ON sedm.StudentIEPAccommodation(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_9fbb10_Id ON sedm.StudentIEPDisability(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_5453a5_Id ON sedm.StudentIEPGoal(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_524fcd_Id ON sedm.StudentIEPServiceDelivery(Id);

