CREATE UNIQUE INDEX IF NOT EXISTS UX_a16a88_Id ON sedm.IDEAEvent(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_dcdf59_Id ON sedm.IEPGoal(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_35f795_Id ON sedm.IEPServiceDelivery(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_3d4921_Id ON sedm.IEPServicePrescription(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_9be3b5_Id ON sedm.StudentIEPAccommodation(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_296761_Id ON sedm.StudentIEPAssociation(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_9fbb10_Id ON sedm.StudentIEPDisability(Id);

